### ISSUE TITLE
Add "cancers" sections to the person menu in pedigrees (for better integration with BOADICEA)

### ISSUE THREAD

**Issue by allasm** [phenotips/phenotips#1071]
Breast  Pink
Ovarian Purple
Colon Brown
Uterus Red
Prostate Yellow
Pancreas Blue
Melanoma Black
Kidney Green
Gastric ??
Lung - Teal
Brain  ??
Oesophagus ??

**Comment by sdumitriu** [comment]
Cancers are not shown in the pedigree legend in view/pdf mode.

**Comment by antonkatz** [comment]
I think the UI needs improvement. The dropdowns should be aligned.

**Comment by allasm** [comment]
Aha, so you also so the unaligned version? In fact they are aligned, but randomly on phenomecentral.org I see them unaligned and CSS inspection shows a wrong CSS is used.

Aside from that, date dropdown should be improved and one legend bug should be fixed, I will create an issue for that

**Comment by antonkatz** [comment]
I just built the master, and I'm using firefox. Maybe the problem is the cache.
