### ISSUE TITLE
Improve support for family studies

### ISSUE THREAD

**Issue by marta-** [phenotips/phenotips#1118]
- [ ] Add a _Family_ page listing all the family members
- [ ] Attach documents/images to the family
- [ ] Maintain symmetrical relationships between linked patients

**Comment by DeanWay** [comment]
@antonkatz @allasm I've done some testing of the family studies features (branch issue-1118), and found a few issues that I thought I'd mention here.

1. When editing a Family if the user presses "save and view summary", there is no button displayed to go back to editing the family. If the user wishes to make changes they have to leave the page and go to a patient in the family and click "open family". There is also no way to edit a family when visiting from the link in the home page section "My Family Data."

2. It seems as though currently there is no way to remove a patient from a Family or delete a Family entirely (other than manually entering /delete/data/(family id) in the url) . This could be relevant if the user accidentally clicks "Create a family", or if two sets of patients are created and added to separate families when in fact they are from the same family, and need to somehow be merged.

3. If the user attempts to add a patient with an existing pedigree to an existing family, an error message is displayed "patient P0000003 already has a different pedigree, and therefore cannot be included in this one." but the patient is added to the family anyway. 
The patient can be removed from that family if the user clicks "Search Again". However, If users saves the page there will simply be an "Open Family" button on the patient form that links to the searched family, the patient does not show up in the family's list of patients, and the pedigrees are not linked. This is somewhat related to issue 2 above, in that the patient can no longer be added to other families

**Comment by DeanWay** [comment]
4 . The "warn about sensitive information" feature should be improved. Currently the only difference between having this feature enabled or not, is that a warning message is displayed when _editing_ the pedigree. The user still sees the same information without warning when viewing the pedigree from the patient form or the family form. Additionally, when the error message is shown in the edit pedigree screen, the pedigree is still quite visible in the background, along with the list of disorders, phenotypes, genotypes, and cancers on the right. 
Perhaps the users should be able to specify which nodes contain sensitive information, and all information from those nodes is hidden until the user clicks on that node and a warning message could be displayed before revealing the information. Perhaps a lock or similar symbol could be shown on those nodes to signify that there is some hidden information that can be shown

**Comment by antonkatz** [comment]
Thank you. This is useful.

**Comment by tmarathe** [comment]
I have found a few more issues with the family studies feature.

1. The patient identifier search bar in "Family Study" (This patient is the ___ of patient with identifier ___ ) does not return any suggestions, even when related patient identifiers exist.

2. Parental ethnicity does not carry over between pedigree and patient record.

3. Family records do not have identifiers like patient records, so they are all listed as "-" in My Family Data.

**Comment by antonkatz** [comment]
1. That's the old family studies. I think there is an issue for that.

2. This is hard since the pedigree has only one field, while the patient
record has maternal and paternal.

3. That is odd. I'll check it out.

**Comment by DeanWay** [comment]
@tmarathe 3. Is not true. When editing the Family there is identifier field

**Comment by DeanWay** [comment]
^ it is somewhat difficult to see since it is at the top of the page and not under a heading

**Comment by allasm** [comment]
> 2.
>
> Parental ethnicity does not carry over between pedigree and patient
> record.
>
>> 2. This is hard since the pedigree has only one field, while the
>> patient record has maternal and paternal.

Yes, it is a known bug/missing feature.

I think this will be resolved when we integarte (not yet developed) new
patient view into pdigree editor (instead of the pop-up person menu)

**Comment by allasm** [comment]
There is a bug with family studies after the latest update.

In the update we allowed patients to be added to  a pedigree even if not all clinicians who have access to the patient have access to all other patients in the pedigree. We now pass permission sets around and those clinicians are only allowed to edit the patients they have access to from within the pedigree editor. But the problem is they now can't save the pedigree, as on save it goes to all the patient records, including those they don't have edit rights to - even if they did not modify anything directly related to those patients. The java part needs to be updated, probably after @itaiGershtansky changes are merged in.
