### ISSUE TITLE
HGNC should be indexed locally for better performance and one less external server dependency

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1159]
Currently HGNC is used as a remote service on genenames.org, exposing a Solr index through two REST APIs, one for searching, which returns just the symbol names, and one for getting information about a specific symbol. This approach has several issues:

- it's slow, especially given that getting information about each gene symbol involves a HTTP connection
- it's an external service, which some institutions won't allow through the firewall
- it's not secure, since it doesn't use encrypted connections
- it's not flexible, since we can't control how to search, causing things like #1616

Given that the full HGNC data is [available](http://www.genenames.org/cgi-bin/statistics), we should index it locally using our own Solr schema.

**Comment by sdumitriu** [comment]
@veronikaslc @allasm Can you two work together on this? @antonkatz knows what's involved in this as well.

**Comment by antonkatz** [comment]
As in adding a re-indexing option into the administration?

**Comment by sdumitriu** [comment]
@antonkatz see the updated issue description.

**Comment by allasm** [comment]
@veronikaslc @antonkatz - should/can/do we have time to discuss this today?

**Comment by antonkatz** [comment]
Can/do - yes
Should - I don't know

**Comment by veronikaslc** [comment]
What about today/tomorrow?
