### ISSUE TITLE
Add an ontology access method for searching terms based on user input

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1162]
The current quick search uses complex queries constructed in JavaScript, which requires copy/pasting code in several places. There should be a Java method (mirrored in the script service) that suggests terms best matching the user's input.

**Comment by allasm** [comment]
Is it supposed to be used everywhere, e.g. here (https://github.com/phenotips/phenotips/blob/master/components/pedigree/resources/src/main/resources/pedigree/view/nodeMenu.js#L111) as well?

**Comment by sdumitriu** [comment]
Yes. There's still some cleanup to do.
