### ISSUE TITLE
Display a nicer error message when the ontology data isn't indexed

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1164]
Currently, when the HPO index is not available, a __failed to execute velocity__ error with a long stacktrace is displayed. A nicer message should be displayed instead.

**Comment by antonkatz** [comment]
When the data is simply not indexed (ex. reindexing with no internet connection) the phenotype display does not fail. It falls back to displaying ids.
The only way I have found to make it fail is by removing the Solr core, in which case several parts of phenotips break down (including the reindexing section in administration).
