### ISSUE TITLE
Inherit the father's last name by default when adding new children

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1265]
Currently, changing the father's name updates existing children as well, but new children will not inherit the name.

**Comment by allasm** [comment]
Need to discuss with Bailey if last names should be propagated to the "last name" or "last name at birth" fields before closing this issue

**Comment by marta-** [comment]
@bgallinger, here's a pedigree editor behaviour issue where we could use your input:
> Need to discuss with Bailey if last names should be propagated to the "last name" or "last name at birth" fields before closing this issue

**Comment by bgallinger** [comment]
I think it should be "last name" and not "last name at birth". When drawing pedigrees, I usually ask for current last name that is on identification (e.g. health card) or name that would help me request medical info if needed.
