### ISSUE TITLE
PhenoTips should warn if a pushed patient is being edited locally

### ISSUE THREAD

**Issue by allasm** [phenotips/phenotips#1281]
E.g. a patient is pushed to PhenomeCentral, then edited locally, then pushed again. Second push will overwrite some fields, possibly losing the changes.

Knowing that a patient was pushed is a good idea in any case, e.g. to search for pushed patients only or to see what was the state of the patient as of last push

**Comment by buske** [comment]
A related comment is that when pushing, if the destination record is going to be overwritten, the differences should somehow be mentioned/highlighted. At least, this is strongly requested by the UDN/Melissa.
