### ISSUE TITLE
Push patient functionality should also push measurements, genes and phenotype details

### ISSUE THREAD

**Issue by allasm** [phenotips/phenotips#1282]
First, people may be expecting this

Second, if a pushed patient is edited on the target server (e.g. measurements are added, which automatically adds certain measurement-based phenotypes) and then pushed again the push will overwrite all phenotypes, while keep the measurements, leaving patient in a non-consistent state where measurements are there but corresponding phenotypes are not selected (related to #1281)

**Comment by buske** [comment]
This is becoming more of a priority now that Bailey has started using this functionality to push from UDPICS to PC.
