### ISSUE TITLE
Status of genes in the Excel export should be color coded

### ISSUE THREAD

**Issue by antonkatz** [phenotips/phenotips#1357]
Should be the same as with phenotypes (yes - green, no - red)

**Comment by sdumitriu** [comment]
Keep in mind that soon we will have more statuses: `affected`, `rejected`, `pending` and `unknown`.

**Comment by antonkatz** [comment]
affected - green
rejected - red
pending - yellow
unknown - gray

That should work I think

**Comment by sdumitriu** [comment]
Make `unknown` black, agreed with the rest.

**Comment by antonkatz** [comment]
I'm going to change only the rejected colour for now, since that's all we have and leave this issue open.

**Comment by sdumitriu** [comment]
Closing since the currently supported gene types are colored. When we'll add pending and unknown gene types, we'll add them with color.
