### ISSUE TITLE
"RP1" gene not indexed (well) by GeneNameService

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1360]
RP1 does not show up when you search for it:
https://phenomecentral.org/get/PhenoTips/GeneNameService?outputSyntax=plain&q=RP1

Even though it is a known gene that the service knows about:
https://phenomecentral.org/get/PhenoTips/GeneNameService?outputSyntax=plain&g=RP1

**Comment by allasm** [comment]
I just tried it - on the first try second link produced a result, then first link did not. But after trying both links again both produced some output. Can it be slow processing?

**Comment by buske** [comment]
They both definitely produce output, it's just that the output is incorrect. The second link shows the details for RP1, correctly, which suggests that the GeneNameService does indeed know about it (it's a valid gene, and it exists in our system). However, the first link doesn't include RP1 among the autocomplete suggestions. Here is the output I get from the first link:
```{"numReturned":10,"docs":[{"symbol":"ABCA4"},{"symbol":"ADAMTS19-AS1"},{"symbol":"ADCY10"},{"symbol":"AHDC1"},{"symbol":"AMER1"},{"symbol":"APOBEC4"},{"symbol":"ARID5A"},{"symbol":"C1orf167"},{"symbol":"C1orf174"},{"symbol":"CA4"}]}```

RP1 is sadly not among those results, even though it is an exact match.

**Comment by sdumitriu** [comment]
The problem is that we're searching different fields with equal weight, and the results we get have `RP1*` as an alias or previous symbol. We need #1162.
