### ISSUE TITLE
Selecting "HP:0012533 Allodynia" as a symptom breaks the diagnosis suggestions

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1372]
- create a new patient
- select a few phenotypes, including HP:0012533 Allodynia
- go to the _Diagnosis_ section
- with _Allodynia_ included in the terms, no diagnosis is displayed
- disabling _Allodynia_ will bring suggestions back

**Comment by buske** [comment]
Is this caused by the term not being present in the version of HPO that BOQA uses?

**Comment by sdumitriu** [comment]
I don't know, I'm "just reporting it".
