### ISSUE TITLE
Allow filtering by maximum privacy level in export (as or more public)

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1378]
This would be very useful for administrators wanting to export patients more public than some threshold (e.g. exclude private, or only export public patients).

**Comment by antonkatz** [comment]
Is this the same issue? https://github.com/phenotips/phenotips/issues/1308

**Comment by buske** [comment]
Yes, apologies.

**Comment by antonkatz** [comment]
Which one should be closed?

**Comment by sdumitriu** [comment]
Usually the older one is kept, unless the newer one has a much better title/description.

**Comment by buske** [comment]
Yep, went with the one that was more descriptive. :)

**Comment by buske** [comment]
Not sure if it's better implemented as a checkbox per privacy level for maximum flexibility, or a dropdown to select maximum level, but I'll let the implementer figure that out.
