### ISSUE TITLE
Add support for storing evidence for candidate genes

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1381]
Language for describing these various levels of evidence is still being decided, but the implementation should likely be tagging functionality, e.g. the ability to tag a candidate gene with 1 or more terms from a standard set (dropdown).

**Comment by buske** [comment]
@mellybelly, @cmungall: Do either of you have an opinion on the ontology or resource we should use to start collecting and encoding this form of evidence?

**Comment by buske** [comment]
Here are three:

biological_relevance=Implicated in relevant biological process
significant_variant=Contains variant of functional significance
known_association=Verified association with relevant phenotype/disease

Anyone have others they strongly feel should be included?

**Comment by veronikaslc** [comment]
Is is the right output for RP1 gene search? (issue #1360):

{"symbol":"ACTR1A","name":"ARP1 actin-related protein 1 homolog A,
centractin alpha
(yeast)","external_ids":{"genecards_id":"ACTR1A","omim_id":"605143","entrez_id":"10121","ensembl_gene_id":"ENSG00000138107"},"alias_symbol":["ARP1,
Arp1A"]}
