### ISSUE TITLE
Patient.xar files are sometimes exported when trying to push a patient to a remote server

### ISSUE THREAD

**Issue by mjshepherd** [phenotips/phenotips#1383]
open patient record
export as XAR 
push to PhenomeCentral

**Comment by sdumitriu** [comment]
Couldn't reproduce. Are you sure about this?

**Comment by mjshepherd** [comment]
Its definitely happening on my instance. But it only happens when pushing a patient after a xar has already been exported

**Comment by antonkatz** [comment]
Does it happen on playground?

**Comment by mjshepherd** [comment]
Also it seems to only happen while editing the patient record
