### ISSUE TITLE
Just creating a patient creates a large number of versions in the history

### ISSUE THREAD

**Issue by meatcar** [phenotips/phenotips#1388]
Simply going through the process of creating a patient creates a large number (5+) versions of the patient in the history view. That's really noisy, and detracts from the usability of the versioning feature.

Ideally, it should commit each change to the same version, until the user is done editing the patient. Any subsequent changes at a later time should be added to new versions.

**Comment by marta-** [comment]
+1!

**Comment by allasm** [comment]
This is related to/a duplicate of #1304
