### ISSUE TITLE
Exported date and last_modification_date should be in ISO format

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1404]
Currently, they are in what I believe is the display format:
```json
"date": "09/29/2013",
"last_modification_date": "11/13/2014"
```

**Comment by sdumitriu** [comment]
What export is that?

**Comment by buske** [comment]
JSON

**Comment by sdumitriu** [comment]
Weird, there's no date being exported at all at the moment...

**Comment by buske** [comment]
Yeah, it looks like an individual patient JSON export doesn't contain that information. Try exporting the database as JSON.
