### ISSUE TITLE
affiliation, referral, and comment not appearing under pending users

### ISSUE THREAD

**Issue by bgallinger** [phenotips/phenotips#1405]
I can only see the user's username, first name, and last name when trying to approve account requests (see screen shot)

![image](https://cloud.githubusercontent.com/assets/8963190/6005398/f5d013e0-aad7-11e4-9141-2fdcdd06207e.png)

**Comment by antonkatz** [comment]
How long has this been going on?

**Comment by bgallinger** [comment]
Not sure, I was able to view everything last Tuesday. Today was the first time since then I have tried to approve account requests

**Comment by antonkatz** [comment]
That's odd. I don't have access to phenomecentral, so this will be on Sergiu's plate to check out.

**Comment by allasm** [comment]
I can confirm all other fields are missing

**Comment by antonkatz** [comment]
After some digging, Andrey and I found out that the code on PhenomeCentral is not the code in the repo; it has been updated and never committed.
The two hypothesis we have are:
1. The connectivity issues are causing this.
2. The update has erased some important changes.

**Comment by bgallinger** [comment]
so is this fixable? I need this information to grant accounts

**Comment by sdumitriu** [comment]
Fixed on PhenomeCentral production, refresh.
