### ISSUE TITLE
Measurements entered by age instead of date

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1417]
At least until PhenoTips is used real-time in the clinic, measurements should be entered by patient age instead of by date. After chatting with C4R, this is their only use case. They have to make up fake dates that are roughly right based on the age at measurement in the clinic notes.

This also solves the problem of having to deal with measurement dates when the birth date is unknown: #1321, #1323.

**Comment by antonkatz** [comment]
Why not keep both the DOB and patient age (mutually exclusive)?

**Comment by buske** [comment]
@antonkatz do you mean date of measurement? We could theoretically accept either, but it'd suggest only showing the date of measurement if the DOB is set, and it might be best to just have entry by age for simplicity. Will defer to @marta- to figure out what's best for the users. :)

**Comment by marta-** [comment]
You are both right :)

If DOB is entered, we will allow the user to enter either the date of measurement or the age at measurement (only one of them of course). If DOB is missing, date of measurement will be disabled/hidden and the user must enter the age at measurement.

**Comment by antonkatz** [comment]
Oh, I see. I misunderstood what was being changed.
