### ISSUE TITLE
Premies should have adjusted measurement ages

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1419]
This was suggested by several people at CHEO. Measurements should be based on the full age of the individual, including gestational age. Thus, children born at gestational age 30 are ~10 weeks younger than a full-term counterpart, and the growth curves should be adjusted.

**Comment by sdumitriu** [comment]
Is this a duplicate of #602, or just a related issue?

**Comment by buske** [comment]
Related issue. This is dominated by #602, but likely much easier to implement. Ideally you have separate data for premies, but in the meantime you can get a first approximation by just adjusting by the difference in gestational age.
