### ISSUE TITLE
Order measurements by age when viewing a patient record

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1424]

**Comment by itaiGershtansky** [comment]
I think it's better to order by date - age requires both date of measurement and date of birth.

**Comment by marta-** [comment]
@itaiGershtansky True. However, in the near future, we will be allowing users to enter the age at measurement as an option to date of measurement (actually as the only option in case date of birth is undefined). At that point, age will always exist. When you fix this issue, I suggest you try to order by age and fallback on the date if some ages are missing. This way it will work now, and also it will be easy to transition to "age at measurement" when that's available.
