### ISSUE TITLE
Record locking

### ISSUE THREAD

**Issue by marta-** [phenotips/phenotips#1442]

**Comment by buske** [comment]
Allow doctors to "lock" a record to prevent any further editing (from them or any other user) until they "unlock" it again.

**Comment by meatcar** [comment]
@DeanWay @JKereliuk @tmarathe have you guys tested this, is it working properly?

**Comment by JKereliuk** [comment]
I tested this a while ago and it appeared to be working correctly.

**Comment by tmarathe** [comment]
I tested record locking also, it is working correctly.
