### ISSUE TITLE
Add a widget for suggesting patient records

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1451]
Combine front-end of standard suggest widget with back-end from patient search widget

**Comment by allasm** [comment]
Currently widgets does not search for blank patients. E.g. searching using "P000" shows all patients except those which have no data at all. Is this expected?

**Comment by antonkatz** [comment]
What is no data at all? No patient object or a patient object with all
fields empty?

**Comment by sdumitriu** [comment]
1. Create new patient
2. Don't save, click away

That's kind of a bug, caused by the fact that a patient record copied from the template doesn't have an `external_id` field, so the join from the query doesn't match the document.

**Comment by allasm** [comment]
I discovered this via new patient creation in pedigree, when a patient is created using velocity:
$services.patients.createNewPatient()

**Comment by allasm** [comment]
Should we split the "template has no external_id" issue into a separate bug/issue then?

**Comment by antonkatz** [comment]
I think so.

**Comment by sdumitriu** [comment]
Yes.
