### ISSUE TITLE
Last minute 1.1-RC1 bugs found

### ISSUE THREAD

**Issue by allasm** [phenotips/phenotips#1471]
1) The filter page is broken (browse all patients -> export as Excel and -> export as JSON)

2) On the patient page the birth date input widget is sometimes displayed as a bunch of drop-downs (as intended?) but sometimes as a text input box (still figuring out how to reproduce that consistently)

**Comment by sdumitriu** [comment]
2) might have been a browser cache issue, can't reproduce it.
