### ISSUE TITLE
VCF upload does not filter before upload

### ISSUE THREAD

**Issue by antonkatz** [phenotips/phenotips#1472]
When trying to attach an image or a pdf, the file is validated before being uploaded, i.e. selecting a .doc will warn that the file is not supported. But when uploading a vcf, any file is successfully uploaded, it just won't be shown as a .vcf attachment afterwards.

**Comment by buske** [comment]
@antonkatz Could you clarify?

**Comment by sdumitriu** [comment]
@buske You can upload any file, except that only `.vcf` will be shown in the __upload and manage__ dialog. So uploading a `.pdf` will work, but the file is not displayed. This causes confusion (where did the file go), garbage (if it can't be seen, it can't be deleted), and even missing data (the user believes the file is uploaded, but it is not actually registered as the patient's VCF, so it won't be processed).

The pre-upload filter works based on MIME types, and there's no standard MIME for `.vcf`, other than the `vcard file` one which is not correct and not supported on all systems/browsers. This might have to wait until the whole upload is redesigned.

**Comment by buske** [comment]
@sdumitriu Yeah, sorry. There originally wasn't a description, back when I posted that comment. It's clear now. :)

**Comment by antonkatz** [comment]
Is there a chance that by the time we redesign it, we could forget about support for IE9?
