### ISSUE TITLE
MIM disorders not appearing in pedigree key

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1480]
When the pedigree was created prior to the latest version.
After editing the pedigree and re-saving, they re-appear.
Might be a problem with migration?
Reported by Courtney.

**Comment by buske** [comment]
Noticed in: https://playground.phenotips.org/bin/P0001748

**Comment by sdumitriu** [comment]
The legend is a new-ish feature, it requires data that wasn't recorded by the older pedigree. So yes, it's normal that old pedigrees don't have a legend. Is this what you're describing?

**Comment by buske** [comment]
Yes, the feature was in the ~10 March release, and pedigrees created before that date didn't display the MIM disorders in the key. It sounded like other things were displaying in the key though, just not the disorders.

**Comment by allasm** [comment]
If Orion refers to the key/legend inside the pedigree editor (not on the patient page), that feature is old and there were only minor changes to it, all not relatd to disorders.

Am I right that to reproduce this we need to find a patient created in the previosu version on playground, open it, get no disorder in the legend, save, re-open and get disorder in the legend?
