### ISSUE TITLE
Spell checking is not working properly in some cases

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1485]
For example, "der" returns "Ataxia" as the top hit. Unclear why.

Reported by @marta-

**Comment by allasm** [comment]
I saw a few more examples of this, e.g. looking for "sdfsdf" (a random string) returns "#308800 KERATOSIS FOLLICULARIS SPINULOSA DECALVANS, X-LINKED" as the suggested disorder in the disorder picker (in my locla copy, on playground it also suggests a few other keratosis disorders)

**Comment by antonkatz** [comment]
Potentially has to do with this commit https://github.com/phenotips/phenotips/commit/056eb9563bf02e7a0c6414c5a3eb662079d1536a

**Comment by antonkatz** [comment]
I think I fixed it.
