### ISSUE TITLE
Clarify hierarchy structure of inheritance terms

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1486]
It is not clear to some new users why the inheritance term options are indented and organized in this way. Having some lines or rethinking this display might help.

Reported by Veronika.

**Comment by marta-** [comment]
Same issue for age of onset.

![issue2](https://cloud.githubusercontent.com/assets/651980/6923582/8e6b18f8-d7a0-11e4-8565-1c470a7889a3.png)
![issue1](https://cloud.githubusercontent.com/assets/651980/6923583/8e6e3844-d7a0-11e4-8e37-5b5e800882ad.png)

**Comment by danielpgross** [comment]
@buske, are you able to provide more details about the cause of confusion here? Specific feedback from these users would be very useful.

Based on what I see now, some improvements might be to:
- provide clearer visual separation between root nodes on the hierarchy tree
- automatically check off all ancestor nodes when a leaf node is checked (this actually might apply to the tree in "Clinical symptoms and physical findings" as well)

**Comment by buske** [comment]
If I recall, Veronika's suggestion was some sort of line indicator like what is used in old file system viewers:

![image](http://i.imgur.com/ZBOKk.png)

Alternatively, checking off ancestor nodes could be possible, but that doesn't fit the radio button UI, and I think it will cause more trouble than good when involving the Clinical symptoms section. Further, it requires the user to actually click something in order to understand it. I'd suggest going for a visual cue.

**Comment by marta-** [comment]
Indeed, that was the suggestion. However we should not introduce a new hierarchy style, but remain consistent with the look from the ontology browser.

**Comment by danielpgross** [comment]
To remain consistent with the ontology browser but still introduce a visual cue for the hierarchical nature of the information, it looks like the only option is to use the arrow symbols used by the ontology browser:
![p0000001___phenotype_database](https://cloud.githubusercontent.com/assets/4006062/7163917/c0850a76-e36a-11e4-906e-ef7f388a5824.png)

What do you think of this solution?
