### ISSUE TITLE
Underscore behaves very strangely in Identifier filtering

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1504]
* Specifying "80" in the Identifier filter box shows all records with "80" as a substring. 
* Specifying "80-" works as expected (showing any results with that as a substring)
* Specifying "80." works as expected (showing any results with that as a substring)
* Specifying "80_" *does not*, and shows results without an underscore.

Even more bizarrely, adding underscores somehow changes the meaning, such that "80__" returns different results and "80________" returns different results (neither of which necessarily have an underscore in the result).

**Comment by mjshepherd** [comment]
It seems that underscore behaves as a wildcard character. The reason results change when you type more of them is because the identifiers aren't long enough to match any of those characters.
Is this still an issue?

**Comment by buske** [comment]
This is not a critical issue, but I find it obnoxious and I try to use "_" in Identifier filtering frequently, for example, to get all the patients from a specific cohort.

**Comment by buske** [comment]
@sdumitriu This is still broken on PhenomeCentral. Searching for "UDP_3741" does not return the exact match, but searching for "3741" works.

**Comment by buske** [comment]
This is appears to be an incomplete fix. Searching for "_" on the playground yields many cases without underscores in the identifier, suggesting the identifier is not being treated literally. Further, filtering by underscore still appears to be very broken on PC.

**Comment by sdumitriu** [comment]
Where exactly do you search? In the quick patient search in the header?

**Comment by buske** [comment]
In the Identifier filter field, in AllData.

**Comment by buske** [comment]
The quick patient search was a different issue, #1518.
