### ISSUE TITLE
No protection against concurrent edits on same patient record

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1517]
Patient records do not lock when being edited by multiple people. Since I don't think the changes are being merged and propagated, this means that one person's edits are getting wiped without warning, which isn't good.

**Comment by sdumitriu** [comment]
That's not true, when a user starts editing a patient record a lock is placed on it.

**Comment by buske** [comment]
Okay, sorry, I was checking this with two browsers but the same user account.

**Comment by buske** [comment]
When I use two browsers on playground.phenotips, they collide as well. Are all the anonymous users the same user (and if so, why do we need the `open` privacy level)?

**Comment by sdumitriu** [comment]
By default, anonymous users don't have access to patient records, not even if they're `open`. The playground is explicitly configured to allow guests to create and edit patient records without the need to create an account.

`open` means that all __registered__ users can edit the patient record.

**Comment by sdumitriu** [comment]
And yes, all guests are the same user.
