### ISSUE TITLE
Pedigree legend is not displayed properly in some browser/OS combinations

### ISSUE THREAD

**Issue by allasm** [phenotips/phenotips#1562]
E.g. Chrome/Windows does not display round coloured circles but empty boxes.

The likely problem is that we reference FreeSerif font which is probably not available:
e.g.:
<span class="pedigree-disorder-color" style="color: #949ab8; margin: 0 .5em 0 0; font-family: FreeSerif, serif;">⬤</span>

**Comment by sdumitriu** [comment]
Note that the PDF export doesn't know how to handle complex CSS. Worst case, the legend could display different things in export mode and the other modes.

**Comment by danielpgross** [comment]
@sdumitriu I'm thinking of two options:
- use an HTML element with constant width & height, background color, and border radius 50%
- use [```fa-circle```](http://fortawesome.github.io/Font-Awesome/icon/circle/)

Which of these is better from the perspective of the PDF export?

**Comment by sdumitriu** [comment]
None. Do this:

```
#if ($xcontext.action == 'export')
  the char that is there now
#else
  one of the two alternatives you proposed
#end

**Comment by danielpgross** [comment]
I see, thanks.
