### ISSUE TITLE
Unable to link parent to child in family study when identifier has a # or _

### ISSUE THREAD

**Issue by bgallinger** [phenotips/phenotips#1567]
See screenshots

I can find the patient that I need to link to 
![screen shot 2015-04-14 at 4 14 28 pm](https://cloud.githubusercontent.com/assets/8963190/7146425/715b0f44-e2c1-11e4-9709-d5ee746c8090.png)
![screen shot 2015-04-14 at 4 13 25 pm](https://cloud.githubusercontent.com/assets/8963190/7146427/724071a6-e2c1-11e4-8315-6a74ac31421d.png)

when I just type in "ALSIS" but not when I type "1_ALSIS"

**Comment by antonkatz** [comment]
Might be the same issue:
Underscore behaves very strangely in patient quick search #1518

**Comment by sdumitriu** [comment]
I cannot reproduce this, it works correctly for me.
