### ISSUE TITLE
Navigating by tab from the month of birth to the day takes two tabs

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1572]

**Comment by marta-** [comment]
@tmarathe @DeanWay can you confirm this is fixed?

**Comment by tmarathe** [comment]
Yes, it is working properly now.

**Comment by sdumitriu** [comment]
Did you try in Firefox and Chrome?

**Comment by veronikaslc** [comment]
I did Chrome Version 43.0.2357.130 m, FireFox Version 38.0.5,
