### ISSUE TITLE
Information about Solved cases is not included in the Excel export

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1575]
The whole Excel export is unmaintainable...

**Comment by antonkatz** [comment]
We should hook it onto the controllers somehow.

**Comment by antonkatz** [comment]
There are 3 types of data holders for controllers. Map, List, and Simple. My guess would be that creating functions that can format those into excel shouldn't be overly complex.
Disorders and phenotypes will probably need to be custom formatted, just like they are for the JSON.

Then there are headers left. Is that something we can put into the controller?
