### ISSUE TITLE
Closing the pedigree should return to the previous mode (view or edit)

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1580]
Since #1577, it is now possible to edit the pedigree directly from view mode. However, when closing the pedigree, it always goes back into editing the patient record.

(Use the `xback` parameter to keep track of the URL where it should go back to)

**Comment by allasm** [comment]
Not sure about what "xback" is, but XWiki.contextaction stroes the last mode used and an be used in a getURL to get the proper mode URL. If this is fine the issue can be closed.
