### ISSUE TITLE
UI: "New patient record" page: re-arranging/formatting "Prenatal and perinatal history" section look

### ISSUE THREAD

**Issue by veronikaslc** [phenotips/phenotips#1594]
- "Gestation at delivery (weeks):" label is too far from its input field and input field is too long for values from  0 to 38.
- Gestation at delivery (weeks) input can have only numerical values, but no input validation is done, any character can be even saved
- "APGAR score (1/5 minute):" labels are too far from its input field
- NA/Y/N labels are not in one color: black or grey
- "Premature birth ": why do we hide only 2 subsequent info lines? Why not show them without hiding?
- "Gestation at delivery (weeks): " if set to less than 38 is not automatically adjusting the "Premature birth" NA/Y/N input to "Y" value

**Comment by DeanWay** [comment]
Additionally, under the prenatal growth parameters section, the Abnormal birth length, weight, and head circumference can have both fields set to yes and yes, or no and no even though they are mutually exclusive.
![screen shot 2015-05-19 at 3 39 16 pm](https://cloud.githubusercontent.com/assets/11419228/7712188/ba2a6c50-fe3d-11e4-9c3c-6034a960575c.png)

**Comment by sdumitriu** [comment]
@DeanWay That's issue #346
