### ISSUE TITLE
viewer=xml causes unfriendly XML Parsing Error

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1609]
e.g. XML Parsing Error: XML or text declaration not at start of entity
Location: https://phenomecentral.org/bin/F0000013?viewer=xml
```
Line Number 179, Column 9:        <?xml version="1.0" encoding="UTF-8"?>
--------^
```

**Comment by sdumitriu** [comment]
That's normal, use `xpage=xml` instead.

`viewer` selects what's displayed inside the rest of the HTML, between the header and the footer.
`xpage` selects who generates the whole response.
