### ISSUE TITLE
"Mode of inheritance" is no longer exported in the Excel file

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1612]
Probably caused by the fact that it changed from single select to multiple select.

The Excel export will have to be updated too.

**Comment by sdumitriu** [comment]
@antonkatz issue titles are for end users, not about implementation details. What would a user understand from "no longer loaded by the respective controller"?

**Comment by antonkatz** [comment]
I see. Nonetheless the title is wrong.
The export was broken everywhere.
