### ISSUE TITLE
Publish XWiki JavaScript event when the value of the specificity widget score on the patient form changes

### ISSUE THREAD

**Issue by shendrix** [phenotips/phenotips#1613]
It would be useful if a JavaScript event is published (observable in the same way as other XWiki events http://platform.xwiki.org/xwiki/bin/view/DevGuide/JavaScriptAPI) when the value of the specificity score changes as the user edits a patient record.

Our use case is the we are embedding Phenotips in an iframe and want to provide UI feedback in our page based on the score. Currently we listen for the event 'xwiki:actions:save' and parse the specificity score from #specificity-meter title attribute, but having a specific event carrying the value of the score would be more robust.

**Comment by sdumitriu** [comment]
Done:

```
document.observe('phenotips:specificity-meter:change', function(event) {
  console.log(event.memo.value, event.memo.level);
});
