### ISSUE TITLE
Pedigree should have a setting for number of pages when printing

### ISSUE THREAD

**Issue by antonkatz** [phenotips/phenotips#1624]

**Comment by allasm** [comment]
Isn't it more a question of zoom levels not number of pages? E.g "fit on one page" or "zoom in an din" until it eventually occupies 1x2 or 1x3 or 3x1 or 2x3 or whatever pages, depending on the shape?

**Comment by antonkatz** [comment]
Ask Mike as to what exactly they wanted

**Comment by marta-** [comment]
@allasm the goal is to have an easy way to print large pedigrees while keeping them readable. Basically there should be a "print preview" where they can zoom until reaching the desired size, and the preview should be clearly split into pages. Please note that it's much more likely for the pedigree to be too wide than too tall.
