### ISSUE TITLE
Measurement date picker months horribly broken

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1629]
On PhenoTips playground:

1. Months change on you when editing a date
  - create a new patient record
  - select August 1, 2015
  - click edit to open picker, will appear as **July 31, 2015**
2. 30-day months disappear
  - select April 1, 2015
  - click edit to open picker, **no days in April will appear** (days from March appear twice, then May)

**Comment by mjshepherd** [comment]
This issue is no longer reproducible

**Comment by sdumitriu** [comment]
This depends on the current date, so try to set your system to 2015-04-27 first.
