### ISSUE TITLE
The number of twins added for a new partneship is not intuitive

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1637]
Adding twins to an existing node is obvious: select `n` twins, you'll get `n` new twins for a total of `n+1` in that pregnancy.

But when adding twins under a partnership, as a new pregnancy, the same behavior is used. which is not intuitive: select `n` twins, end up with `n+1` children.

There should be a lower limit of 2 twins after fixing this, since having 1 twin in a pregnancy is just a simple pregnancy.

**Comment by mslasm** [comment]
I think 806cd5ddb4f4a0a81cd03ddc6ff36852332c36a2 fixed it, did you check a version after that commit?

**Comment by sdumitriu** [comment]
I did, testing the 1.2M3 release.

**Comment by mslasm** [comment]
OK, will check tomorrow

**Comment by sdumitriu** [comment]
I checked on the playground (1.2M3), I still get "n+1" new children, with min(n)==1.

**Comment by allasm** [comment]
I just tried playground, worked as I described it?

**Comment by allasm** [comment]
(i.e. when "1" is selected parents are added (if not there yet) and 1 new node is created, and marked as a twin of a current node for a total of 2 twins)

**Comment by sdumitriu** [comment]
Yes, works correctly for "k", but not for "n" (adding twins under a partnership).

**Comment by allasm** [comment]
Aaaah, yes, I see. My reading skills need an update, I did not get the "under a partnership" part correctly and totally forgot partnership nodes have a dot as well

**Comment by sdumitriu** [comment]
@allasm Should this go in 1.1.2 as well?

**Comment by allasm** [comment]
The fix is not a cherry-pick for 1.1.x, as a few other lines committed as part of other issues are required for this to work (those other lines were not bug-fixes but minor improvements) - so a manual update is required pulling lines for a few different commits. Should it still be included?

**Comment by sdumitriu** [comment]
No, it's fine without it.
