### ISSUE TITLE
Case owner/reporter/editor should be links to user profile pages

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1642]
For example, in the following case, I think that each of the users mentioned should be links to the corresponding user profile pages.

![image](https://cloud.githubusercontent.com/assets/4251264/7461994/32ff8a02-f27c-11e4-88a6-ffb600a451b2.png)

**Comment by buske** [comment]
@sdumitriu That's what I figured, but I thought that it was relevant enough to do it. It includes the contact details, which is nice, as well as the list of recent activity and a messaging mechanism. It would also be nice to include a list of (public?) patients the user owns. I'd say reported, but ownership means more. Though I'm not sure how this would work with workgroups owning things.

**Comment by sdumitriu** [comment]
The activity and messaging are gone in the latest version.
