### ISSUE TITLE
Autocomplete widgets should search on paste

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1648]
Currently, you have to press a key to induce autocomplete, but if you paste (for example, a gene name), the autocomplete will not trigger.

**Comment by buske** [comment]
Update: the issue is only when paste is triggered without a keypress. If you paste via keyboard, then autocomplete is still triggered, but if you paste via right-click menu, for example, it doesn't.

**Comment by antonkatz** [comment]
Maybe also listen for this
https://developer.mozilla.org/en-US/docs/Web/Events/input

**Comment by allasm** [comment]
Another long-standing "feature" is that if a single-character input is used, and then field value is cleared and the user enters the same character anew the search is not performed

**Comment by allasm** [comment]
I fixed both issues in the commit below, observing "paste" seems to be a safe quick fix which may only affect pasting, while listening for "input" is more likely to cause some side-effects/interplay between input and other event listeners installed by the widget. Maybe it can be simplified/streamlined, but thatg is a job for another issue

**Comment by antonkatz** [comment]
There's a paste event?

**Comment by allasm** [comment]
There is in most modern browsers (https://developer.mozilla.org/en-US/docs/Web/Events/paste)

The catch is that at the time event is fired input value is not yet set to the pasted value, and accessing pasted content may fail even if a browser supports the paste event itself. There is a workaround which I used though (see the code)
