### ISSUE TITLE
Add checkbox for unknown date of death

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1652]
Clinicians, especially when recording patients from older records or publications, frequently know that the patient is deceased, but the date is unknown. 

I'd suggest this be implemented as a checkbox for "unknown date of death", rather than a checkbox for deceased that then enables entering the date, since my guess is the common case is a known death date.

**Comment by sdumitriu** [comment]
@antonkatz @allasm If this is checked, the patient is supposed to be dead, so I think the pedigree should also mark the patient as deceased. Can one of you look into that?

**Comment by marta-** [comment]
@allasm please sync the pedigree node with the "unknown date of death" field so that we can close this issue today.

**Comment by marta-** [comment]
Postponing this fix for next release.
