### ISSUE TITLE
Add "Other" as an option for the patient's sex

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1654]

**Comment by allasm** [comment]
TODO: also update push functionality, matchmaking and pedigree handling of the "sex" field values

**Comment by marta-** [comment]
@CourtneyHum Please list the possible options for "other" patient sex here.

**Comment by itaiGershtansky** [comment]
From looking at the code, I'm guessing there might be some problems when a patient with sex "other" is a parent.

**Comment by CourtneyHum** [comment]
I am proposing a greater number of options in the field “Sex” based on a literature review and consultation with Riyana Babul-Hirji, CCGC, and Dr. David Chitayat who work in the Multidisciplinary Urogenital Clinic at Sick Kids. 

In 2006, the Lawson Wilkins Pediatric Endocring Society and the European Society for Paediatric Endocrinology consensus group proposed the new Chicago classification of Disorders of Sex Development (DSD). The nomenclature is based on the primary genetic defect and includes three broad categories. 

![image](https://cloud.githubusercontent.com/assets/11950131/8337061/ae3cd374-1a76-11e5-8d1f-97f3383cac64.png)

There are several papers that reference this Chicago classification and I have included above a table that clearly demonstrates the categories. 

It would seem ideal to include the three categories as options under a “sex” label of “other”.

The issue of determining corresponding growth chart, however, is not simple when using the three categories outlined in the Chicago classification. The rule used by Dr. Chitayat is with the presence of a Y chromosome, a male growth chart is used, except for individuals with complete androgen insensitivity syndrome (CAIS).

Thus, when “Sex chromosome DSD” is selected and the karyotype entered in the free text field, there would need to be a way to detect the presence or absence of a Y chromosome, or a way for the clinician to indicate if male or female growth charts should be used.

When “46, XY DSD” is selected, the individuals’ measurements should be plotted on a male growth chart, except when CAIS entered in the free text field. Alternatively, CAIS could be an option that appears when 46, XY DSD is selected.

When “46, XX DSD” is selected, a female growth chart is always used.

As a last alternative, there could be a way for the clinician to indicate which growth chart the individual’s measurements should be plotted on, removing the communication between “Sex” and “Measurements”. This could irritate some clinicians who are not aware of the situations in which this would be a useful option. However, if we were to add syndrome-specific growth charts in the future (something that has been requested by Dr. Mendoza) this option would allow an easier transition and not require a link between “Diagnosis” and “Measurements” as well, as the user would always need to select the appropriate growth chart manually.

**Comment by CourtneyHum** [comment]
In summary: 

- Male  
- Female  
- Other 
   -- Sex Chromosome DSD 	     
   -- 46, XY DSD
   -- 46, XX DSD

**Comment by sdumitriu** [comment]
Basic support for `Other` sex has been added, a more detailed list of options will be implemented later.
