### ISSUE TITLE
Rename the ontology-access module and related classes to use "vocabulary"

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1659]
An ontology is more than just a collection of terms, and currently only HPO is an actual ontology, the rest are unstructured vocabularies/nomenclatures.

**Comment by mjshepherd** [comment]
@sdumitriu The script services which used to implement ontology script service now implement the vocabulary script service. This is causing issues as there are references to, for example, $services.ontologies.hgnc in the velocity code. I noticed that you deprecated the ontology script service, should the "sub" script services have been deprecated or updated? If its the latter we need to update the velocity code as well.
