### ISSUE TITLE
Memoir checkboxes in pedigree

### ISSUE THREAD

**Issue by antonkatz** [phenotips/phenotips#1661]
Story:
"I would find it helpful if there was a checkbox on the Pedigree stating 'consanguinity yes/no' so that I could record that I have enquires about this and the answer was negative. Similarly I would find it helpful if there were a checkbox that I could tick stating that there are no family members with similar problems (perhaps with a prompt to record them on the pedigree if the answer is 'yes').
There prompts are a useful aide memoir for clinicians but also a useful way of recording that the appropriate questions have been asked."

**Comment by allasm** [comment]
Consanguinity is recorded for relationships and already has a switch "automatic-yes-no" on the relationship properties dialogue.

As for the other checkbox, it makes sense, but the pedigree itself supposedly represents the best available information about the family. So maybe we should add a "questions" section where patient responses would be recorded, regardless of the state of the pedigree (e.g. in a family patient A may say X and patient b may say Y - btw, as discussed before, we should eventually add support for different properties seen by different patients with family page pedigree showing any conflicts)
