### ISSUE TITLE
Phenotypes not showing up correctly in pedigree

### ISSUE THREAD

**Issue by bgallinger** [phenotips/phenotips#1663]
See screen shot - the node has anxiety, the legend has the proper phenotype but under clinical symptoms:observed phenotypes, it is listed as 'anxiety (with pheochromocytoma)' - a separate HPO term. I chose anxiety but anxiety (with pheo) shows up

![image](https://cloud.githubusercontent.com/assets/8963190/7594703/84bf49ec-f8b0-11e4-80ce-d1f058e27b70.png)

**Comment by bgallinger** [comment]
This is in the SickKids clinical phenotips instance

**Comment by sdumitriu** [comment]
Duplicate of #1515. That instance needs to be upgraded.
