### ISSUE TITLE
Allow using a remote Solr server for indexing vocabularies

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1666]
The embedded Solr instance is better for performance on a multi-core system, since it bypasses transferring data over a network, but adds more pressure on the disk, memory, and CPU usage. Users should be able to easily configure using a remote Solr server.

**Comment by davidbernick** [comment]
Indexes that are updated infrequently (ontologies) are fine to have embedded. Our request for this is mostly for the Patient data as a multi-node setup without shared disk needs to have a unified view of this frequently changing data.
