### ISSUE TITLE
400 Bad Request adjusting collaborator group

### ISSUE THREAD

**Issue by davidbernick** [phenotips/phenotips#1669]
I have a patient.
I go into "modify permissions".
I go to "collaborators".
I go to "new collaborating group" and it autocompletes the group I want.
I then submit "update" and the screen shows me: "Failed to update.Bad Request".

Here's the form data:
transfer-to:"on"
visibility:"private"
user:""
group:""
collaborator:"Groups.udn"
accessLevel:"view"
xaction:"update"
patient:"P0000003"
submit:"Update"
close:"Cancel"

**Comment by davidbernick** [comment]
Additionally -- it appears intemittent. SOmetimes it works, sometimes it doesn't.

**Comment by sdumitriu** [comment]
Do you have anything relevant in the server logs?

**Comment by davidbernick** [comment]
Just "INFO: Error parsing HTTP request header"

**Comment by sdumitriu** [comment]
Can you try to capture the response body, for example with Firebug or the browser's developer tools?

**Comment by sdumitriu** [comment]
Looks like it was a proxy configuration issue.
