### ISSUE TITLE
Inputting an identical identifier in a new patient record and saving displays wrong error message

### ISSUE THREAD

**Issue by kereliuk** [phenotips/phenotips#1680]
When creating a new patient record, if one use an identifier that already exists and clicks save the message "There are 1 missing fields" appears instead of a more informative one about the identifier already existing.
Red text does appear below the input box when one inputs a non unique identifier and this is correct, but it is not the same as when saving.

**Comment by buske** [comment]
Related to: https://github.com/phenotips/phenotips/issues/1496
