### ISSUE TITLE
How to add a left menu item

### ISSUE THREAD

**Issue by simplelive** [phenotips/phenotips#1683]
I want to add a left menu item, How to do?
![7e36 tmp](https://cloud.githubusercontent.com/assets/2071172/7832177/966de302-048f-11e5-9d82-983ecdfa0ac2.png)

**Comment by marta-** [comment]
@simplelive For questions about usage and configuration, please use the ```support@phenotips.org``` mailing list or the ```users@phenotips.org``` mailing list instead of the issue tracker. See also http://phenotips.org/Contact/Mailing+Lists .

**Comment by simplelive** [comment]
Thinks! but i want to modify code, not configuration.
