### ISSUE TITLE
Should be able to specify parents as egg/sperm donor in the pedigree

### ISSUE THREAD

**Issue by mjshepherd** [phenotips/phenotips#1693]

**Comment by CourtneyHum** [comment]
From Bennett et al. (2008). Standardized human pedigree nomenclature: update and assessment of the recommendations of the national society of genetic counselors. J Genet Counsel. 17:424-433.

![image](https://cloud.githubusercontent.com/assets/11950131/7914290/24e2f5b6-0844-11e5-9340-489f67b139e2.png)
