### ISSUE TITLE
Push to PhenomeCentral does not correctly list the groups the user is a part of

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1706]
This functionality, allowing pushing to PhenomeCentral and having the remote patient belong to a group the user is a part of, does not seem to correctly list the groups the user is a part of (or it is cached and does not update when the membership changes).

**Comment by allasm** [comment]
The bug seems to be in the way XWiki adds users to groups (or how groupManager collects user's groups), not in the push component. We debugged this with Sergiu, the problem is that Xwiki user object is missing XWiki: qualifier, or something like that

**Comment by buske** [comment]
Is this the same reason that Sergiu is present in a group twice, once as `xwiki:XWiki.sdumitriu`, and once as `XWiki.sdumitriu`?
