### ISSUE TITLE
Need "metabolic" and "endocrine" section for many HPO terms that currently fall under the heading of "other"

### ISSUE THREAD

**Issue by CourtneyHum** [phenotips/phenotips#1710]
![image](https://cloud.githubusercontent.com/assets/11950131/7922415/1b42e602-087a-11e5-995a-4753e5af5198.png)

**Comment by sdumitriu** [comment]
Looks like a regression of #580. @antonkatz can you look at it?

**Comment by antonkatz** [comment]
There's a pull request for this issue that seems to have no unresolved comments with it.
