### ISSUE TITLE
Minimum test coverage for jacoco

### ISSUE THREAD

**Issue by JKereliuk** [phenotips/phenotips#1711]
In many modules the minimum test coverage ratio value set in the pom file for the jacoco plugin seems arbitrary.
For example, in Push Java APIs the minimum ratio is 1 and there are currently no unit tests for Push Java APIs.
Should we have a standard value for this, have it incremented as we write tests, or remove it all together?

**Comment by sdumitriu** [comment]
It's set by default to 100%, which means that an exact value should be specified in each module if it doesn't have full coverage. However, there's a bug in the plugin, if there are no tests at all, it just assumes that there shouldn't be any tests and the coverage is met.
