### ISSUE TITLE
Need new field in Patient Information for OHIP number 

### ISSUE THREAD

**Issue by CourtneyHum** [phenotips/phenotips#1719]
Any patient having whole-exome sequencing in the Sick Kids lab needs to have an OHIP number in the PhenoTips records. Up until now, clinicians have been putting this as the patient identifier, but now we are encouraging all clinicians to use MRN as the identifier, thus OHIP needs to be a separate, but optional field, as most clinicans will not enter OHIP number unless they are submitting for WES.

**Comment by buske** [comment]
Enabled the field for the SickKids instance.

**Comment by sdumitriu** [comment]
There's already a _health card number _field, which is disabled by default, but can easily be enabled from the administration.
