### ISSUE TITLE
Proband becomes "gender unknown" in the pedigree editor even after gender is specified.

### ISSUE THREAD

**Issue by CourtneyHum** [phenotips/phenotips#1720]
![image](https://cloud.githubusercontent.com/assets/11950131/7967103/1f05c98a-09f6-11e5-98c1-0246a1a4f896.png)

When I close the editor, the proband is correctly labelled as male. But each time I enter the editor he turns back into a diamond.

**Comment by sdumitriu** [comment]
That's "normal", the gender is always taken from the patient record, so you must specify there the gender. The known bug (#1459) is that the gender is not sent back from the pedigree into the patient record.

**Comment by allasm** [comment]
This is already fixed in the family studies branch (which has all of #1459)
