### ISSUE TITLE
Number suffixes for measurement values are incorrect (example: 11st, 12nd, 13rd, etc)

### ISSUE THREAD

**Issue by tmarathe** [phenotips/phenotips#1722]

**Comment by marta-** [comment]
@tmarathe Good catch, and the fix is easy once you get used to the velocity language. Do you want to give it a try? The code responsible for this is here: https://github.com/phenotips/phenotips/blob/master/components/patient-measurements/ui/src/main/resources/PhenoTips/PatientToolsService.xml#L101
