### ISSUE TITLE
Update jacoco version

### ISSUE THREAD

**Issue by JKereliuk** [phenotips/phenotips#1746]
When trying to build front end tests in patient-data/tests jacoco throws the following error.

Failed to execute goal org.jacoco:jacoco-maven-plugin:0.7.2.201409121644:check (jacoco-check) on project patient-data-tests: Error while reading code coverage: Incompatible version 1007. -> [Help 1]

Which is apparently a plugin error that was fixed recently
http://jira.sonarsource.com/browse/SONARJAVA-1091

**Comment by sdumitriu** [comment]
Why is version 0.7.2 used? The version that's configured in our poms is 0.7.5. Maybe something that IDEA does on its own?
