### ISSUE TITLE
Should warn user on refresh of unsaved data loss

### ISSUE THREAD

**Issue by kereliuk** [phenotips/phenotips#1756]
When refreshing the page there is no warning of unsaved data.

We could have something like this, (that I have seen for similar cases around the net), when trying to refresh on unsaved data.
![confirm](https://cloud.githubusercontent.com/assets/9435736/8094472/5bb92ad0-0f95-11e5-90fb-98b056c93bcc.png)

**Comment by buske** [comment]
I think this is **very** important.
