### ISSUE TITLE
Display suggested phenotypes in a browsable list of pages

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1758]
This allows users to see other results outside the top 20.

**Comment by CourtneyHum** [comment]
Do you mean the phenotypes with the lightning bolt? Deleting them is already an option.

**Comment by sdumitriu** [comment]
@CourtneyHum No, the phenotypes showing under "You may want to investigate...", for which the only options currently available are Y and N, which will lead to many negative annotations, something we don't really want.

**Comment by sdumitriu** [comment]
@mjshepherd Useful: https://github.com/phenotips/clinical-text-analysis-extension/blob/master/ui/src/main/resources/PhenoTips/Clinical%20Notes%20Annotation.xml#L332
