### ISSUE TITLE
Can't enter free text in the "quick phenotype search", only in the section-specific search fields

### ISSUE THREAD

**Issue by CourtneyHum** [phenotips/phenotips#1762]
But perhaps this is on purpose?
![image](https://cloud.githubusercontent.com/assets/11950131/8137277/2e54c2f8-1110-11e5-94cd-97fbe24b7154.png)
![image](https://cloud.githubusercontent.com/assets/11950131/8137283/35e1f342-1110-11e5-83ea-422d81829ed9.png)

**Comment by marta-** [comment]
This is on purpose: if we're not in ca phenotype category, we don't know where to place the newly entered text in the summary. The options are:
- always go to "Other"
- prompt the user for more details on the newly entered non standard phenotype before saving it (e.g. "what kind of abnormality is this?", where the user can choose their answer from the top=level abnormalities defined by HPO).

@CourtneyHum Thoughts?

**Comment by CourtneyHum** [comment]
That makes sense, I would leave it the way it is and perhaps let people know that free text terms are permitted only when searching within a specific anatomic system.

**Comment by buske** [comment]
@tmarathe Based on our discussion at today's meeting, we have decided it would be best to:
- get rid of the `other` section and text box in each section
- add "new term" option at the end of quick phenotype search results
- after selecting that option, prompt the user to select a top-level category (or "Other')

**Comment by allasm** [comment]
If we get rid of the "other" section where should terms from the "other" top-level category appear?

**Comment by tmarathe** [comment]
> add "new term" option at the end of quick phenotype search results

By this you mean that we add the non-standard term that the user has typed, correct? And then they should be prompted to classify it in one of the categories (or "Other").

**Comment by CourtneyHum** [comment]
I don't think we are getting rid of the Other section. We are getting rid of the "other" search box within each category.

**Comment by buske** [comment]
@allasm What Courttney said. Sorry for phrasing that poorly.

@tmarathe That is correct. We have an option at the end of the list of suggestions, to add the term as a non-standard term (like we currently do for the 'other' boxes).

**Comment by tmarathe** [comment]
@buske 
The top-level categories displayed are configurable (i.e. users can specify additional categories in administration), so when prompted to classify a custom term should we just present the generic (default) options, or include the user specified categories as well?

**Comment by buske** [comment]
@marta- Thought a modal might be reasonable, but your dislike of modals is well-known. Do you have a proposal for dealing with this list of 10-20 categories to choose from?
