### ISSUE TITLE
Warning in measurements section is alarming

### ISSUE THREAD

**Issue by CourtneyHum** [phenotips/phenotips#1763]
I'm not sure I feel that there is a strong reason to note that "It is recommended to record weight, height and head circumference for all patients."

The yellow warning symbol catches me off guard each time. Clinicians should know to put in weight, height and head circumference, and are not reminded on paper charts to do so. I think that by rearranging the layout of the measurements section we can make these three fields the first and easiest to fill, indicative of their importance. At the very least, the message should go away after weight, height and head circumference data is entered.

I'm open to hearing others' thoughts on this issue.

**Comment by marta-** [comment]
We can easily disable the warning so it wouldn't be displayed by default if you think this is best.

**Comment by mjshepherd** [comment]
@marta- @CourtneyHum What is the consensus on this? Removing it is easy but I feel that is was added for a purpose. Adding an enable/disable option is possible but would have to be in the Admin menu, which I feel is a bit of overkill.

We could make the text less alarming pretty easily or add a "dismiss" button. Or the text could appear briefly as a notification upon opening the measurements section.

In any case, will this be necessary after the measurement section redesign?

**Comment by sdumitriu** [comment]
I think it should be an `info` and not a `warning` message.

**Comment by sdumitriu** [comment]
It won't be needed after the redesign, but it's a quick fix to make it less alarming for 1.2
