### ISSUE TITLE
Option to export pedigree only and de-identifed pedigree 

### ISSUE THREAD

**Issue by CourtneyHum** [phenotips/phenotips#1764]
I heard before that you were working on this. Just had a few thoughts:

When a record is exported to PDF, growth charts appear on individual pages. It would be great if the pedigree did the same, rather than be incorporated within the family history section. The pedigree should also be in landscape orientation. 

It would be great if there was the option to print/export to PDF just the pedigree in landscape orientation and the option to print/export with all identifiers removed - Only shading and arrow indicating proband remaining. 

Even better (but more complex) would be to allow checkboxes for the user to indicate what info can be included, much like the options for database export to Excel or JSON.

**Comment by marta-** [comment]
Exporting the just the pedigree is planned for 1.3. We'll try to implement some of the other suggestions as well.

**Comment by CourtneyHum** [comment]
Excellent!

On Mon, Jun 15, 2015 at 11:25 AM, Marta Girdea <notifications@github.com>
wrote:

> Exporting the just the pedigree is planned for 1.3. We'll try to implement
> some of the other suggestions as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phenotips/phenotips/issues/1764#issuecomment-112107642>
> .
>



-- 
Courtney Hum
Genetic Counsellor

PhenomeCentral Support Team

**Comment by marta-** [comment]
@allasm please feel free to split into smaller tasks and reassign.
