### ISSUE TITLE
Add "Allergies – environmental, food, medication" question to "Medical history" section

### ISSUE THREAD

**Issue by kimsplinter** [phenotips/phenotips#1775]

**Comment by davidbernick** [comment]
Make sure that you roll these changes into UDN branch.

**Comment by marta-** [comment]
static list with https://github.com/phenotips/phenotips/blob/master/components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml#L3257 as custom display

**Comment by itaiGershtansky** [comment]
Is there a list of allergies to put in the static list?

**Comment by sdumitriu** [comment]
Not yet.
