### ISSUE TITLE
Rearrange siblings within the same generation in the pedigree

### ISSUE THREAD

**Issue by allasm** [phenotips/phenotips#1787]
Via drag and drop likely

**Comment by oleraj** [comment]
This would be a nice feature to have.  Is there any workaround in the meantime, other than deleting all of the children and adding them from scratch?

**Comment by sdumitriu** [comment]
If the age of each individual is known, then auto-arranging should put them in order of their age. Other than that, there is currently no solution.

**Comment by marta-** [comment]
https://phenotips.atlassian.net/browse/PT-2205
