### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by DaveSanders** [phenotips/phenotips#1791]
I'm sorry to post this as an issue, but where do I start with accessing an API into the system?  We're working with a customer to push patient data into the system, but the API docs on Phenotips.org don't exist, and while we can post data to the site, we run into issues when mimicking a web client in our code.

We'd much rather use an API to send this data in, but can't find any information on where to start...

Thanks

**Comment by marta-** [comment]
https://phenotips.org/AdminGuide/Integration

Also this is coming soon: https://github.com/phenotips/phenotips/issues/1160

Please use the support mailing list for future questions: https://phenotips.org/Contact/
