### ISSUE TITLE
Add fields for "upper segment", "lower segment" and automatic calculation of US:LS ratio

### ISSUE THREAD

**Issue by CourtneyHum** [phenotips/phenotips#1795]
Centiles for US and LS not necessary. Physicians interested in value of US:LS ratio as it is increased in short-limbed dwarfism and rickets.

**Comment by sdumitriu** [comment]
@CourtneyHum I think this should trigger HP:0008873 above a certain value; do you happen to know that value?

**Comment by CourtneyHum** [comment]
@sdumitriu It would depend on age and race
![image](https://cloud.githubusercontent.com/assets/11950131/8385778/c3d1e5dc-1c18-11e5-91d4-71057d77c2d1.png)
