### ISSUE TITLE
Add field for internipple distance, chest circumference and calculate internipple index

### ISSUE THREAD

**Issue by CourtneyHum** [phenotips/phenotips#1796]
Internipple index = (internipple distance x 100) / chest circumference

**Comment by sdumitriu** [comment]
@CourtneyHum HP:0006610 (wide intermamillary distance) should be selected for a large index. Do you know what's the threshold for that? And should there be a term added to HPO for a small index?

**Comment by CourtneyHum** [comment]
@sdumitriu Marta says you have an electronic copy of Judith Hall.

Someone at the NIH was discussing this with Bailey...whether or not there is a term for small intermamillary distance...I'll have to get back to you on that
