### ISSUE TITLE
Add field for middle finger length

### ISSUE THREAD

**Issue by CourtneyHum** [phenotips/phenotips#1797]
Used to assess for brachydactyly

**Comment by sdumitriu** [comment]
@CourtneyHum Do we have a reference chart for this?

**Comment by CourtneyHum** [comment]
Should be in Judith Hall

**Comment by sdumitriu** [comment]
Any triggers? I see HP:0009461 Short 3rd finger, but nothing for long middle finger.

**Comment by CourtneyHum** [comment]
What do you mean by triggers?

A short middle finger alone could be classified as HP:0009461 short 3rd finger but the measurement is commonly used to confirm an subjective appearance of short fingers (overall, all five) HP:0000248 Brachydactyly

**Comment by CourtneyHum** [comment]
@sdumitriu A long middle finger may be used to confirm a subjective appearance of arachnodactyly HP:0001166

**Comment by sdumitriu** [comment]
"Triggers" means that when an abnormal measurement is detected, a phenotype is selected. For example, "short stature" is selected when the last height measurement is below -2SD.

**Comment by CourtneyHum** [comment]
HP:0000248 Brachydactyly
HP:0001166 Arachnodactyly

Probably good as defaults, and clinicians can delete if they don't feel it fits, or if there is something more specific, like a short third finger only, or brachydactly type A, B, or C...
