### ISSUE TITLE
When selecting multiple consecutive custom terms, in view mode they appear all in the same row

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1812]
![custom-terms](https://cloud.githubusercontent.com/assets/88663/8613962/e5fd5868-26b2-11e5-8d16-305209c6d7d4.png)

**Comment by marta-** [comment]
https://github.com/phenotips/phenotips/blob/master/components/patient-tools/src/main/java/org/phenotips/tools/FormField.java#L106

There should be a separate `span` with the`fa*` css classes instead of giving those css classes to the element containing the custom term.
