### ISSUE TITLE
Handle obsoleted HPO terms more gracefully

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1813]
It appears that right now, we keep obsoleted term as a regular ID (rather than, for example, migrating it to non-standard terms). This is not ideal, since we should probably reserve the regular feature ID section for valid HPO terms.

Here is one example:
`{"id":"HP:0200135","label":"obsolete Macrocephaly due to hydrocephalus","type":"phenotype","observed":"yes"}`

**Comment by buske** [comment]
In this particular case, the term ID has been added as an alt_id for another term, and should be migrated:

```
id: HP:0000256
name: Macrocephaly
alt_id: HP:0005491
alt_id: HP:0005496
alt_id: HP:0200135
```

**Comment by danielpgross** [comment]
Duplicate of https://genomequebec.mcgill.ca/jira/browse/PT-41
