### ISSUE TITLE
PhenoTips installer does not run with Mac OSX 10.10

### ISSUE THREAD

**Issue by CourtneyHum** [phenotips/phenotips#1852]
`"To view this web content, you need to install the Java Runtime Environment"`

Unfortunately, even after downloading the latest JRE (version 8, update 51).

Documentation on the internet says to install the legacy Apple JRE (version 6) instead.

After doing this, PhenoTips crashes on launch with:
`LSOpenURLsWithRole() failed with error -10810 for the file /Applciations/PhenoTips.app`

--Orion

**Comment by buske** [comment]
This is not reproducible on my Mac. Seems to be an issue with the Java installation.

**Comment by sdumitriu** [comment]
@mjshepherd Can you see if you can reproduce this?

**Comment by mjshepherd** [comment]
@sdumitriu @buske @CourtneyHum This is not reproducible on my mac either.

**Comment by buske** [comment]
It was a Java 6 vs Java 8 issue, where installing the JRE by following the popup link didn't resolve the problem.

**Comment by sdumitriu** [comment]
The stacktrace says that you're using Java6.

The most likely issue is that you don't have the appropriate java set as the default (even if the Systems Preference panel claims that you do). You can diagnose this as follows: open your search bar, and search for Terminal. Run the terminal application, this will give you a command prompt. At the prompt type "java -version". If either it cannot find java, or gives the version as <1.7 then we have identified the problem.

If the version reported is < 1.7 (or no java is found), you need to install the appropriate **Java Developer Kit** (note: not the runtime environment). You can get it here:

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Once you download and install it, it should all start working, automagically. 

If you don't want to install the JDK, you may be able to point java to the right version by defining the JAVA_HOME variable in your ~/.bash_profile or ~/.bashrc file, with something like:

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.XXX/Contents/Home

(search for the right directory name)
