### ISSUE TITLE
Phenotips Build Failure

### ISSUE THREAD

**Issue by monkollek** [phenotips/phenotips#1855]
[INFO] PhenoTips - HSQLDB Database ........................ FAILURE [01:09 min]
[INFO] PhenoTips - War package ............................ SKIPPED
[INFO] PhenoTips - Standalone Distribution ................ SKIPPED
[INFO] PhenoTips - DMG Distribution ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26:04 min
[INFO] Finished at: 2015-08-01T17:34:18-04:00
[INFO] Final Memory: 193M/2557M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.phenotips:phenotips-packager-maven-plugin:1.0-milestone-5:import (default) on project database-zip: Failed to import XAR dependencies: Failed to lookup component [org.xwiki.context.internal.DefaultExecutionContextManager] identified by [role = [interface org.xwiki.context.ExecutionContextManager] hint = [default]]: Failed to lookup component [role = [interface org.xwiki.context.ExecutionContextInitializer] hint = [velocity]]: Failed to lookup component [org.xwiki.velocity.internal.DefaultVelocityContextFactory] identified by [role = [interface org.xwiki.velocity.VelocityContextFactory] hint = [default]]: Failed to lookup component [org.xwiki.velocity.internal.DefaultVelocityConfiguration] identified by [role = [interface org.xwiki.velocity.VelocityConfiguration] hint = [default]]: Failed to lookup component [org.xwiki.configuration.internal.DefaultConfigurationSource] identified by [role = [interface org.xwiki.configuration.ConfigurationSource] hint = [default]]: Failed to lookup component [org.xwiki.configuration.internal.DocumentsConfigurationSource] identified by [role = [interface org.xwiki.configuration.ConfigurationSource] hint = [documents]]: Failed to lookup component [org.xwiki.configuration.internal.WikiPreferencesConfigurationSource] identified by [role = [interface org.xwiki.configuration.ConfigurationSource] hint = [wiki]]: Failed to lookup component [org.xwiki.wiki.internal.descriptor.DefaultWikiDescriptorManager] identified by [role = [interface org.xwiki.wiki.descriptor.WikiDescriptorManager] hint = [default]]: Failed to lookup component [org.xwiki.wiki.internal.descriptor.document.DefaultWikiDescriptorDocumentHelper] identified by [role = [interface org.xwiki.wiki.internal.descriptor.document.WikiDescriptorDocumentHelper] hint = [default]]: Failed to lookup component [org.xwiki.query.internal.DefaultQueryManager] identified by [role = [interface org.xwiki.query.QueryManager] hint = [default]]: Failed to lookup component [org.xwiki.query.internal.DefaultQueryExecutorManager] identified by [role = [interface org.xwiki.query.QueryExecutorManager] hint = [default]]: Failed to lookup component [com.xpn.xwiki.internal.query.ConfiguredQueryExecutorProvider] identified by [role = [javax.inject.Provider<org.xwiki.query.QueryExecutor>] hint = [default]]: Failed to lookup component [com.xpn.xwiki.store.hibernate.query.DefaultQueryExecutor] identified by [role = [interface org.xwiki.query.QueryExecutor] hint = [default]]: Failed to lookup component [com.xpn.xwiki.store.hibernate.query.HqlQueryExecutor] identified by [role = [interface org.xwiki.query.QueryExecutor] hint = [hql]]: Failed to lookup component [com.xpn.xwiki.store.hibernate.DefaultHibernateSessionFactory] identified by [role = [interface com.xpn.xwiki.store.hibernate.HibernateSessionFactory] hint = [default]]: PermGen space -> [Help 1]

======

mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T07:57:37-04:00)
Maven home: /usr/local/apache-maven-3.3.3
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.4", arch: "x86_64", family: "mac"

**Comment by sdumitriu** [comment]
The last line in the log holds the answer: `PermGen space`. As stated in the [build instructions](https://github.com/phenotips/phenotips#building-instructions):

> It is advisable to increase the amount of memory available to Maven: `export MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=256m"`
