### ISSUE TITLE
IE9 reports some JS errors when loading the patient edit page

### ISSUE THREAD

**Issue by allasm** [phenotips/phenotips#1880]
In version 1.2M5

**Comment by allasm** [comment]
1.2M5 has those errors. 1.2-Snapshot (~1.2-RC1) does not.

This seems to be related to "xwiki:dom:updated" event, for which in 1.2M5 in IE9 "event.memo.elements" contains an array with just one element which is "undefined".

I fixed our code which handles "xwiki:dom:updated" events in a few different places, undefined will now be simply ignored. But since the root cause has likely been fixed elsewhere in 1.2-RC1, I di dnot fix or investigate similar errors produced in the xwiki.js code.

**Comment by sdumitriu** [comment]
Fixed by f2c7e604260fa021bf0a0e455479bc9ed9bf2c3c.
