### ISSUE TITLE
Please add a StudyBindingClass object to PatientTemplate by default

### ISSUE THREAD

**Issue by alexhenrie** [phenotips/phenotips#1898]
The "Study" button should always be there so that patients can be created, then moved into studies at a later date. Currently there is no good way to move an existing patient with no study into a new study.

If you're worried about cluttering the user interface, you can make the button only appear visually if at least one study is defined.

**Comment by buske** [comment]
I'll let others comment on the feasibility of adding this to the PatientTemplate by default in the source. I expect the thought is sufficient to be able to add it on a per-installation basis. If you'd like to enable studies, you should add it to the PatientTemplate and migrate existing patients.

The easiest way to migrate patients would be with a script along the following lines (untested... apologies if it has errors):
```
{{groovy}}
for (id in services.query.xwql('from doc.object(PhenoTips.PatientClass) as patient \
    where patient.identifier >= 0 \
    and doc.space = \'data\' \
    order by doc.fullName').execute())
  {
    def p = services.patients.getPatientById(id);
    def doc = xwiki.getDocument(p.document);
    def study = doc.getObject('PhenoTips.StudyBindingClass', true);
    doc.save();
    println "Ensured patient has StudyBindingClass: [[${id}]]";
  }
{{/groovy}}
```
