### ISSUE TITLE
Customising phenotips interface

### ISSUE THREAD

**Issue by pontikos** [phenotips/phenotips#1947]
How would one go about customising the phenotips interface?

**Comment by sdumitriu** [comment]
Customizing the patient record: log in with an administrative user, go to Administration -> Patient form structure. You can disable and reorder fields, but adding new fields is a bit more complicated. Don't forget to click Save.

Customizing the phenotypes shown by default in the patient record: log in with an administrative user, go to Administration -> Phenotypes displayed by default, type a new name for your configuration (e.g. Ophthalmology phenotypes), click on Create. You must enter a mapping as a JSON, there is some documentation in there as a sample stub mapping.
