### ISSUE TITLE
mvn install fails on windows

### ISSUE THREAD

**Issue by johntiger1** [phenotips/phenotips#2323]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.295 s
[INFO] Finished at: 2017-06-08T17:13:01-04:00
[INFO] Final Memory: 60M/483M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (license-resources) on project phenotips-parent: Error downloading resources archive. Could not transfer artifact org.phenotips:phenotips-license-resources:jar:1.6 from/to phenotips-releases (https://nexus.phenotips.org/nexus/content/repositories/releases/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[ERROR] org.phenotips:phenotips-license-resources:jar:1.6
[ERROR]
[ERROR] from the specified remote repositories:
[ERROR] phenotips-releases (https://nexus.phenotips.org/nexus/content/repositories/releases/, releases=true, snapshots=false),
[ERROR] phenotips-snapshots (https://nexus.phenotips.org/nexus/content/repositories/snapshots/, releases=false, snapshots=true),
[ERROR] phenotips-externals (https://nexus.phenotips.org/nexus/content/groups/public/, releases=true, snapshots=false),
[ERROR] central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by sdumitriu** [comment]
Can you post the output of `mvn -version` please?

**Comment by johntiger1** [comment]
Thanks for the response:

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: C:\Program Files (x86)\apache-maven-3.3.9\bin\..
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_66\jre
Default locale: en_CA, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

**Comment by veronikaslc** [comment]
you may want to install `Java version: 1.8.0_131`

**Comment by johntiger1** [comment]
Updated java but no success sadly

**Comment by marta-** [comment]
So what does `mvn -version` output now?

Also, do you get the same error as before (failure to connect to nexux)?

**Comment by sdumitriu** [comment]
Make sure you update the JDK also, not just the JRE.

**Comment by johntiger1** [comment]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.686 s
[INFO] Finished at: 2017-06-09T16:18:41-04:00
[INFO] Final Memory: 47M/240M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (license-resources) on project phenotips-parent: Error downloading resources archive.: Could not transfer artifact org.phenotips:phenotips-license-resources:jar:1.6 from/to phenotips-releases (https://nexus.phenotips.org/nexus/content/repositories/releases/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[ERROR]   org.phenotips:phenotips-license-resources:jar:1.6
[ERROR]
[ERROR] from the specified remote repositories:
[ERROR]   phenotips-releases (https://nexus.phenotips.org/nexus/content/repositories/releases/, releases=true, snapshots=false),
[ERROR]   phenotips-snapshots (https://nexus.phenotips.org/nexus/content/repositories/snapshots/, releases=false, snapshots=true),
[ERROR]   phenotips-externals (https://nexus.phenotips.org/nexus/content/groups/public/, releases=true, snapshots=false),
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by johntiger1** [comment]
The advice to update fixed it! (I had to change my JAVA_HOME and javac path, even after installing the new JDK, since mvn was using the old one still)

Thank you everyone, it works now.
