### ISSUE TITLE
Multiple File Uploads

### ISSUE THREAD

**Issue by CopyrightSplash** [phenotips/phenotips#2360]
Hello,

I don't know what is wrong but I am trying to upload multiple files into PhenoTips and it says error without a reason.The JSON file has no erorrs after looking by eye and with an online tool and individually the uplaod but with the error of the patient number. Do I need to find a way to give each file the number assigned by PhenoTips to continue. The files are generated using a code from data obtained from a survey

Many Thanks

Lori

**Comment by marta-** [comment]
Hi Lori,

Can you tell us what version of PhenoTips you're using? Thanks.

**Comment by marta-** [comment]
Could be [this issue](https://phenotips.atlassian.net/browse/PT-3261). Do you have any "%" characters in the JSON?

**Comment by CopyrightSplash** [comment]
Hello @marta- I am using PhenoTips 1.3 and no I do not have any '%'
