### ISSUE TITLE
Error 404 - Not Found. No context on this server matched or handled this request.

### ISSUE THREAD

**Issue by Denly** [phenotips/phenotips#2504]
Hi our team is trying to run phenotips. My coworker and I both can't run it and got this error.
env:
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
(My coworker is java 8)

error:
Error 404 - Not Found.

No context on this server matched or handled this request.
Contexts known to this server are:
/ ---> o.e.j.w.WebAppContext{/,[file:/Applications/PhenoTips.app/Contents/Resources/phenotips-standalone-1.3.6/webapps/phenotips/, jar:file:/Applications/PhenoTips.app/Contents/Resources/phenotips-standalone-1.3.6/webapps/phenotips/WEB-INF/lib/font-awesome-4.2.0.jar!/META-INF/resources/, jar:file:/Applications/PhenoTips.app/Contents/Resources/phenotips-standalone-1.3.6/webapps/phenotips/WEB-INF/lib/jquery-1.11.1.jar!/META-INF/resources/, jar:file:/Applications/PhenoTips.app/Contents/Resources/phenotips-standalone-1.3.6/webapps/phenotips/WEB-INF/lib/jstree-3.0.8.jar!/META-INF/resources/, jar:file:/Applications/PhenoTips.app/Contents/Resources/phenotips-standalone-1.3.6/webapps/phenotips/WEB-INF/lib/requirejs-2.1.15.jar!/META-INF/resources/, jar:file:/Applications/PhenoTips.app/Contents/Resources/phenotips-standalone-1.3.6/webapps/phenotips/WEB-INF/lib/xwiki-platform-job-webjar-7.1.4.jar!/META-INF/resources/, jar:file:/Applications/PhenoTips.app/Contents/Resources/phenotips-standalone-1.3.6/webapps/phenotips/WEB-INF/lib/xwiki-platform-tree-webjar-7.1.4.jar!/META-INF/resources/]},/Applications/PhenoTips.app/Contents/Resources/phenotips-standalone-1.3.6/jetty/../webapps/phenotips [failed]

**Comment by Denly** [comment]
Ah it is Java 9's issue, my coworker is actually version 9 too. May need to update "runs on 1.7+" in document.  Thanks!

**Comment by sdumitriu** [comment]
PhenoTips 1.4 will work on Java 9, see https://phenotips.atlassian.net/browse/PT-3630
