### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by Zoe-Hou** [phenotips/phenotips#2584]
F:\phenotips-phenotips-1.3.6>mvn install
[INFO] Scanning for projects...
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.6/wagon-webdav-jackrabbit-2.6.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.6/wagon-webdav-jackrabbit-2.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.6/wagon-webdav-jackrabbit-2.6.pom (5.2 kB at 4.6 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/apache/maven/wagon/wagon-providers/2.6/wagon-providers-2.6.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-providers/2.6/wagon-providers-2.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-providers/2.6/wagon-providers-2.6.pom (2.7 kB at 6.5 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/apache/maven/wagon/wagon/2.6/wagon-2.6.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon/2.6/wagon-2.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon/2.6/wagon-2.6.pom (20 kB at 31 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/apache/jackrabbit/jackrabbit-webdav/2.5.2/jackrabbit-webdav-2.5.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/jackrabbit/jackrabbit-webdav/2.5.2/jackrabbit-webdav-2.5.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/jackrabbit/jackrabbit-webdav/2.5.2/jackrabbit-webdav-2.5.2.pom (4.9 kB at 11 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/apache/jackrabbit/jackrabbit-parent/2.5.2/jackrabbit-parent-2.5.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/jackrabbit/jackrabbit-parent/2.5.2/jackrabbit-parent-2.5.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/jackrabbit/jackrabbit-parent/2.5.2/jackrabbit-parent-2.5.2.pom (30 kB at 60 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.pom (2.7 kB at 6.4 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/slf4j/slf4j-parent/1.7.2/slf4j-parent-1.7.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.7.2/slf4j-parent-1.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.7.2/slf4j-parent-1.7.2.pom (12 kB at 27 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.pom
Downloading from central: https://repo.maven.apache.org/maven2/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.pom (7.8 kB at 18 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/commons-codec/commons-codec/1.2/commons-codec-1.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.2/commons-codec-1.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.2/commons-codec-1.2.pom (3.8 kB at 9.0 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/slf4j/jcl-over-slf4j/1.7.2/jcl-over-slf4j-1.7.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/slf4j/jcl-over-slf4j/1.7.2/jcl-over-slf4j-1.7.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/slf4j/jcl-over-slf4j/1.7.2/jcl-over-slf4j-1.7.2.pom (1.9 kB at 4.4 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/commons-lang/commons-lang/2.6/commons-lang-2.6.pom
Downloading from central: https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.pom (17 kB at 40 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/apache/commons/commons-parent/17/commons-parent-17.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/17/commons-parent-17.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/17/commons-parent-17.pom (31 kB at 67 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/apache/apache/7/apache-7.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/apache/7/apache-7.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/apache/7/apache-7.pom (14 kB at 33 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/commons-io/commons-io/2.2/commons-io-2.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/2.2/commons-io-2.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/2.2/commons-io-2.2.pom (11 kB at 25 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/apache/commons/commons-parent/24/commons-parent-24.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/24/commons-parent-24.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/24/commons-parent-24.pom (47 kB at 95 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/apache/apache/9/apache-9.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/apache/9/apache-9.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/apache/9/apache-9.pom (15 kB at 35 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/apache/maven/wagon/wagon-provider-api/2.6/wagon-provider-api-2.6.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-provider-api/2.6/wagon-provider-api-2.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-provider-api/2.6/wagon-provider-api-2.6.pom (1.7 kB at 4.1 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.pom (3.1 kB at 7.4 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/codehaus/plexus/plexus/3.2/plexus-3.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/3.2/plexus-3.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/3.2/plexus-3.2.pom (19 kB at 43 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/sonatype/spice/spice-parent/17/spice-parent-17.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/sonatype/spice/spice-parent/17/spice-parent-17.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/sonatype/spice/spice-parent/17/spice-parent-17.pom (6.8 kB at 16 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/sonatype/forge/forge-parent/10/forge-parent-10.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/sonatype/forge/forge-parent/10/forge-parent-10.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/sonatype/forge/forge-parent/10/forge-parent-10.pom (14 kB at 31 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.6/wagon-webdav-jackrabbit-2.6.jar
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.jar
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/apache/jackrabbit/jackrabbit-webdav/2.5.2/jackrabbit-webdav-2.5.2.jar
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/commons-io/commons-io/2.2/commons-io-2.2.jar
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/commons-codec/commons-codec/1.2/commons-codec-1.2.jar
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/apache/maven/wagon/wagon-provider-api/2.6/wagon-provider-api-2.6.jar
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.6/wagon-webdav-jackrabbit-2.6.jar
Downloading from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/2.2/commons-io-2.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/jackrabbit/jackrabbit-webdav/2.5.2/jackrabbit-webdav-2.5.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/2.2/commons-io-2.2.jar (174 kB at 200 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.jar (26 kB at 24 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.2/commons-codec-1.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-webdav-jackrabbit/2.6/wagon-webdav-jackrabbit-2.6.jar (34 kB at 31 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-provider-api/2.6/wagon-provider-api-2.6.jar
Downloaded from central: https://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.2/commons-codec-1.2.jar (30 kB at 19 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.jar
Downloaded from central: https://repo.maven.apache.org/maven2/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar (305 kB at 192 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-provider-api/2.6/wagon-provider-api-2.6.jar (53 kB at 30 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/jackrabbit/jackrabbit-webdav/2.5.2/jackrabbit-webdav-2.5.2.jar (326 kB at 167 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.jar (284 kB at 138 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.jar (232 kB at 87 kB/s)
Downloading from phenotips-externals: https://nexus.phenotips.org/nexus/content/groups/public/org/phenotips/phenotips-functional-tests-lifecycle/1.1/phenotips-functional-tests-lifecycle-1.1.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/phenotips/phenotips-functional-tests-lifecycle/1.1/phenotips-functional-tests-lifecycle-1.1.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.phenotips:phenotips-functional-tests-lifecycle:1.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.phenotips:phenotips-functional-tests-lifecycle:jar:1.1 @
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as reportPlugins parameter. @ line 1275, column 26
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.phenotips:phenotips-parent:1.3.6 (F:\phenotips-phenotips-1.3.6\pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.phenotips:phenotips-functional-tests-lifecycle:1.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.phenotips:phenotips-functional-tests-lifecycle:jar:1.1: Could not transfer artifact org.phenotips:phenotips-functional-tests-lifecycle:pom:1.1 from/to phenotips-externals (https://nexus.phenotips.org/nexus/content/groups/public/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

**Comment by Zoe-Hou** [comment]
Is there other people have met the same problem? If met, how do you resolve it.

**Comment by Zoe-Hou** [comment]
mvn -version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T15:58:13+08:00)
Maven home: D:\software\apache-maven-3.5.2\bin\..
Java version: 1.8.0_05, vendor: Oracle Corporation
Java home: D:\java\jdk1.8.0_05\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "windows"

**Comment by sdumitriu** [comment]
This is caused by the fact that:
- nexus.phenotips.org uses certificates signed by Let's Encrypt, a relatively new HTTPS signing authority
- you use an outdated version of Java (1.8.0u05) which doesn't list Let's Encrypt as a trusted signing authority

You should update your Java to the latest version (1.8.0u162) to fix this problem.

**Comment by Zoe-Hou** [comment]
@sdumitriu ok. After update my Java to the latest version (1.8.0u162), above problem has been resolved. However when I execute "mvn install", I encountered another problem.

[INFO] There is 1 error reported by Checkstyle 6.19 with checkstyle.xml ruleset.
[ERROR] src\main\java\org\phenotips\tools\jetty\listener\NotifyListener.java:[0] (misc) NewlineAtEndOfFile: 文件未以空行结尾。

**Comment by sdumitriu** [comment]
Did you get the sources with git, or as a downloaded zip?

**Comment by Zoe-Hou** [comment]
Yes, I download the zip from the github. And I checked the file that all the newlines are the LF format. Then I'll execute the mvn according to your suggestions. Thank you so much!

**Comment by Zoe-Hou** [comment]
Yes, it has done when I use "mvn install -Dcheckstyle.skip". Thank you!
