### ISSUE TITLE
Error 500 when run instance

### ISSUE THREAD

**Issue by Zoe-Hou** [phenotips/phenotips#2585]
When Run a custom built instance, it reported as follow:

Starting Jetty on port 8080, please wait...
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=192m; support was removed in 8.0
2018-03-08 17:24:15,325 [main] ERROR .o.i.DefaultObservationManager - Failed to lookup listeners
org.xwiki.component.manager.ComponentLookupException: Failed to lookup component [role = [interface org.xwiki.observation.EventListener] hint = [boqainitializer]]
        at org.xwiki.component.embed.EmbeddableComponentManager.getInstanceMap(EmbeddableComponentManager.java:216)
        at org.xwiki.component.embed.EmbeddableComponentManager.getInstanceList(EmbeddableComponentManager.java:198)

Are there anyone met the same problems?

**Comment by mas-dse-pjmulroo** [comment]
If anyone else has this problem found we needed to remove the temp files to get it working. In windows that was %AppData%/phenotips. The app created it again on next launch and all was good.

**Comment by buske** [comment]
Thank you for sharing @mas-dse-pjmulroo and glad you were able to find a solution.

@Zoe-Hou does this work for you? The full path of the directory you can try removing/renaming is likely: C:\Users\<YOUR_USER>\AppData\Roaming\PhenoTips

Please note, this will delete all patients in your local PhenoTips instance.

**Comment by buske** [comment]
I'm going to close this issue as resolved. @Zoe-Hou, if the issue persisted, please re-open and we can continue debugging.
