### ISSUE TITLE
Text mining feature

### ISSUE THREAD

**Issue by Masber** [phenotips/phenotips#2788]
Hi,

According to [PhenoTips 1.4 Milestone 1 Released](https://phenotips.org/Blog/PhenoTips+14+Milestone+1+Released)

> Text mining: HPO terms are now extracted from "Indication for referral" and "Medical history" and displayed as phenotype suggestions under SUGGESTIONS FROM CLINICAL NOTES box

I am guessing I need to install the "Core text analysis UI" extension to get use of the text mining feature however the instalaltion fails>

> This version is not compatible with your installation.
> Search for a compatible version by going through the list of "Stable Versions" located in the extension's "Description" tab.

> Dependency [com.fasterxml.jackson.core:jackson-core-2.5.4] is not compatible with core extension [com.fasterxml.jackson.core:jackson-core-2.4.0]

Please advise

**Comment by Masber** [comment]
Hi,

any advise on this?

am I right assuming that core text analysis UI extension needs to be installed for the Text mining feature to work?
why Core text analysis UI extension fails during isntallation on phenotips 1.4.1?


thank you very much

**Comment by buske** [comment]
@Masber Thank you for pointing out this discrepancy, and very sorry for the confusion. The text analysis extension was pulled from the 1.4 build and is no longer part of the release. The release notes have been updated accordingly.

**Comment by Masber** [comment]
thank you @buske,

is there a plan to add it back or a way to get same functionality? it looks like very nice feature to have! :)
