### ISSUE TITLE
We couldn't find any extension with id 'org.phenotips:phenotips-ui' and version '1.4.3'.

### ISSUE THREAD

**Issue by castdy** [phenotips/phenotips#2846]
Hi,

I am a novice engineer at a public health service, and I've been asked to setup Phenotips for our researchers. I have downloaded the latest version of Phenotips (1.4.3) and deployed it at our existing Tomcat instance running on Windows 2016 server, and configured Phenotips for a MySQL database. We don't have Maven and I deployed the war through the Tomcat manager.  AFAIK the Tomcat was installed with the default settings for Windows. 

On the initial setup of Phenotips on the browser I get the following error. I've followed the basic steps in the installation guide but could there be something I've missed? 

We couldn't find any extension with id 'org.phenotips:phenotips-ui' and version '1.4.3'. Make sure you have the right extension repositories configured.

The application is deployed on a host that has internet access with a proxy configured, but it is not exposed to the Internet. Is there something I need to configure on the network?

Dominic

**Comment by buske** [comment]
Hi Dominic,

Sorry you've run into this issue. Yes, that's precisely the issue.

Here's a nice explanation from an old support email from @sdumitriu:

> The PhenoTips application comes in two parts, the Java code, and the UI,
> which happens to be found in the database. The standalone distribution
> comes with a pre-packaged database, but if you install PhenoTips on your
> own database, then the UI needs to be fetched from a repository and
> imported into the database. Normally, the repository is the official one
> at https://nexus.phenotips.org. If the server is not totally blocked
> from the internet, it would be easier to add a firewall exception to let
> it connect to this repository: nexus.phenotips.org (192.75.158.4)

We'll create an FAQ for this.

**Comment by castdy** [comment]
Great, creating a firewall rule solved the issue, Thank you! 

Dominic
