### ISSUE TITLE
Attending Signoff

### ISSUE THREAD

**Issue by dadams1** [phenotips/phenotips#570]
Rationale: Records need to have a final "owner" who attests to the records accuracy and state of completion. In a clinical setting, this is usually an attending physician. Furthermore, designation of an attending physician and a signed-off status allows for a search of incomplete records by any given attending.

Request: Please add attending physician box, which designates a system user. This should be required for new records, and should show up on the initial screen. Please add a second element that specifies whether the attending physician has signed off on the report. This element should be a prominent two-state object at the top of each entry. Finally, there needs to be a way to search for "attending AND signoff state". 

Please place this update at high priority as we need it to assure phenotips record integrity.

**Comment by buske** [comment]
Urgent for Care4Rare Activity 2.

**Comment by dadams1** [comment]
Was there some text/explanation associated with this email?

___________________________________________________________
David Adams, MD, PhD
(Pediatrics, Genetics, Biochemical Genetics)
Deputy Director of Clinical Genomics
Office of the Clinical Director/ NHGRI,
MGB/NHGRI, UDP/NIH
Building 10, Room 10C103E, MSC 1851
National Institutes of Health
Bethesda, MD, 20892-0001
(o) 301 402 6435
(c) 301 312 0000
800-NIH-BEEP pin 14657 (NIH pager)
david.adams@mail.nih.gov<mailto:david.adams@mail.nih.gov>
__________________________________________________________

**Comment by buske** [comment]
@dadams1 Just that this functionality, specifically the ability to mark a record as "done," is important for implementing new functionality in the Care4Rare activity 2 instance.

**Comment by dadams1** [comment]
I have no idea what you are talking about.

___________________________________________________________
David Adams, MD, PhD
(Pediatrics, Genetics, Biochemical Genetics)
Deputy Director of Clinical Genomics
Office of the Clinical Director/ NHGRI,
MGB/NHGRI, UDP/NIH
Building 10, Room 10C103E, MSC 1851
National Institutes of Health
Bethesda, MD, 20892-0001
(o) 301 402 6435
(c) 301 312 0000
800-NIH-BEEP pin 14657 (NIH pager)
david.adams@mail.nih.gov<mailto:david.adams@mail.nih.gov>
__________________________________________________________

**Comment by marta-** [comment]
Apologies for all the unsolicited emails. You are receiving them because
you created the "attending signoff" issue on the main PhenoTips issue
tracker: https://github.com/phenotips/phenotips/issues/570. The issue is
still open because the implementation is not finalized, as the UDP
requested only a partial implementation for this feature. We are now
marking its completion as priority because it's being requested by another
research project, and you are receiving emails about all changes and
comments on the issue you created.

If you don't wish to receive such emails in the future, you could turn off
notifications from your github account settings:
https://help.github.com/articles/about-notifications/

I hope this helps clarify.

Have a nice weekend!

**Comment by dadams1** [comment]
Hi Marta,

No, that is absolutely perfect. I just needed a little context. I will look up my signin information and refresh my memory. I probably put that in years ago at this point and didn’t remember what the context was.

Thanks!

-David

___________________________________________________________
David Adams, MD, PhD
(Pediatrics, Genetics, Biochemical Genetics)
Deputy Director of Clinical Genomics
Office of the Clinical Director/ NHGRI,
MGB/NHGRI, UDP/NIH
Building 10, Room 10C103E, MSC 1851
National Institutes of Health
Bethesda, MD, 20892-0001
(o) 301 402 6435
(c) 301 312 0000
800-NIH-BEEP pin 14657 (NIH pager)
david.adams@mail.nih.gov<mailto:david.adams@mail.nih.gov>
__________________________________________________________

**Comment by dadams1** [comment]
Hi Marta,

Just as follow up, I think that this has been present and functional in our instance for a long time now. We have an attending and a “primary clinician” sign off and we use them extensively in UDPICS.

You have a good weekend too,

-David

___________________________________________________________
David Adams, MD, PhD
(Pediatrics, Genetics, Biochemical Genetics)
Deputy Director of Clinical Genomics
Office of the Clinical Director/ NHGRI,
MGB/NHGRI, UDP/NIH
Building 10, Room 10C103E, MSC 1851
National Institutes of Health
Bethesda, MD, 20892-0001
(o) 301 402 6435
(c) 301 312 0000
800-NIH-BEEP pin 14657 (NIH pager)
david.adams@mail.nih.gov<mailto:david.adams@mail.nih.gov>
__________________________________________________________

**Comment by buske** [comment]
Hi David, Yes, my apologies! I wasn't thinking about the emails it was sending you and was just adding additional notes to the GitHub page for this issue so that we can monitor its status. All the best, Orion.

**Comment by dadams1** [comment]
No problem! -David

________________________________
