### ISSUE TITLE
Replace all usages of the deprecated HPOScriptService with the new ontology access services

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#719]
- find all mentions of the `HPOScriptService` class name in `.java` files, and replace either with the `@Named("hpo")` `OntologyService`, or with the more generic `OntologyManager` if all that is needed is the `resolveTerm` method
- find all mentions of `services.hpo` in `.xml` files, and replace either with the `$services.ontologies.hpo`, or with the more generic `$services.ontologies` if all that is needed is the `resolveTerm` method

Check that all the methods being invoked are supported by the new APIs, since they are not 100% compatible with the older ones.

**Comment by antonkatz** [comment]
This issue has some work done, and is pending the resolution of issue-1162

**Comment by antonkatz** [comment]
This issue might be finished. Not sure.

**Comment by antonkatz** [comment]
What is left to fix with this issue?
