### ISSUE TITLE
Last modification time not exportable

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#765]
After the Heidelberg demo, I needed the last modification *times* to know which patients were entered first vs. second for each user, but this information doesn't appear to be exportable. Could this be added, either in the same field or another one?

**Comment by sdumitriu** [comment]
This seems to be fixed now, both the Excel and JSON exports have the last modification date.

As for being able to sort by that column, you can do add it from the _Administration -> Data tables_ page.
