### ISSUE TITLE
The patient symptoms index should preserve the ontology hierarchy

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#825]
Currently the patient index only stores the actual symptoms, which makes it impossible to match patients with closely related, but not exactly the same phenotypes. Instead of storing a simple list of terms, the full hierarchy from the HPO should be stored somehow, similar to how [path hierarchies are stored](http://lucene.apache.org/core/4_6_0/analyzers-common/org/apache/lucene/analysis/path/PathHierarchyTokenizerFactory.html).

**Comment by buske** [comment]
Replaced by https://phenotips.atlassian.net/browse/PT-825
