### ISSUE TITLE
Make the Pedigree editor a standalone application

### ISSUE THREAD

**Issue by marta-** [phenotips/phenotips#841]
... that can be plugged into PhenoTips as well as function on its own.

**Comment by fxp** [comment]
Any progress?

**Comment by marta-** [comment]
Hi @fxp, we have abandoned this issue tracker in favor of https://phenotips.atlassian.net/projects/PT/issues/. This particular ticket has moved to https://phenotips.atlassian.net/browse/PT-841 , so you can follow scheduling and progress there. Quick answer to your question: we did some work to facilitate making the pedigree a standalone application, but we're not quite there yet. This ticket is not considered a high priority at the moment and will be on hold for the next few months.
