### ISSUE TITLE
Report on all phenotypes saved

### ISSUE THREAD

**Issue by mellybelly** [phenotips/phenotips#961]
It would be great if we could view one list of all the phenotypes saved in a record somewhere inside of PhenoTips. Right now, the "current selection" only records what is in the clinical signs and symptoms and not in the other sections. Perhaps a report, made available by clicking somewhere, could be implemented that shows everything being saved out? This will be helpful for troubleshooting implementation into other systems such as UDPICs.

**Comment by mellybelly** [comment]
Any chance this could be bumped in priority? Thanks!

**Comment by buske** [comment]
@mellybelly If the primary use case for this is debugging, the JSON export should be sufficient as it shows all terms, regardless of the category. Is this satisfactory, or is something "prettier" necessary?
